package crabster.rudakov.sberschoollesson27hwk.utils

object Constants {

    const val NOTIFICATION_CHANNEL_ID = "AUDIO_RECORDER_CHANNEL"
    const val NOTIFICATION_CHANNEL_NAME = "AUDIO_RECORDER"
    const val NOTIFICATION_ID = 1
    const val NOTIFICATION_PLAYER_ID = 2
    const val NOTIFICATION_PLAYER_CHANNEL_ID = "AUDIO_PLAYER_CHANNEL"
    const val NOTIFICATION_PLAYER_CHANNEL_NAME= "AUDIO_PLAYER"
    const val REQUEST_RECORD_AUDIO_PERMISSION = 200
    const val ACTION_START_RECORDING = "ACTION_START_RECORDING"
    const val ACTION_STOP_RECORDING = "ACTION_STOP_RECORDING"

}